name: CI - test & build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        if: exists('requirements.txt')
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run tests
        run: |
          if [ -f pytest.ini ] || [ -d tests ]; then
            pip install pytest
            pytest -q
          else
            echo "No tests detected; skipping pytest."
          fi
